Update Change Log
w3c/wot-discovery pull request #351
Opened 2022-06-14 17:53 UTC by mmccool

- Add in two sections, one for changes since FPWD in Nov 2020, one since last WD a year ago in June 2021.
- Looked through commit logs to try and identify major changes
- I may have missed some things, or put them in the wrong category, let me know in the comments.

2022-06-20 12:27 UTC, farshidtz requested changes

2022-06-20 13:42 UTC, mmccool commented on index.html
> +      </ul>
I updated my PRs with points for pagination, events API, TD expiry, and HEAD.  "TM refactoring" was already included ("use TM instead of TD" point).

2022-06-27 13:28 UTC, mmccool commented on index.html
> +      </ul>
I added a "Refactor Directory API" item to capture the above.

2022-06-27 14:09 UTC, farshidtz approved these changes

2022-06-27 14:16 UTC, merged