Update DNS-SD section
w3c/wot-discovery pull request #405
Opened 2022-09-01 11:05 UTC by k-toumura

Fix #403 
- Use table for describe service names.
- Clarified correspondence between service names and protocols.
- Remove Editor Notes in DNS-SD section.
- Update Assignment Notes in 11.2 Service Name Registration to describe an usage of  `_directory` subtype.

Remaining issues:
- Should we use separate service names for HTTPS and CoAPS?
  - for example: `_wot-tls._tcp` and `_wot-dtls._udp` (like [CoRE-RD](https://www.rfc-editor.org/rfc/rfc9176.html#section-4.1.2))
- Should we support CoAP over TCP and CoAP over TLS?
  - for example: `_wot-coap._tcp` and `_wot-coap-tls._tcp`
- (If we add the above, do we have two (or more) implementations for them?)

2022-09-02 18:28 UTC, mmccool requested changes

2022-09-02 18:28 UTC, mmccool commented on images/sequence-dnssd-directory.puml
> +Directory ->  Consumer : mDNS resp.\n"_directory._sub._wot._tcp.local PTR dir._wot._tcp.local"\n"dir._wot._tcp.local SRV 1 0 80 tdir.local"\n"dir._wot._tcp.local TXT td=/.well-known/wot;type=Director
Expand "resp." to "response" to be clearer (pls also regen images...)
```suggestion
Directory ->  Consumer : mDNS response\n"_directory._sub._wot._tcp.local PTR dir._wot._tcp.local"\n"dir._wot._tcp.local SRV 1 0 80 tdir.local"\n"dir._wot._tcp.local TXT td=/.well-known/wot;type=Directory"
```

2022-09-02 18:28 UTC, mmccool commented on images/sequence-dnssd-thing.puml
> +Thing ->  Consumer : mDNS resp.\n"_wot._tcp.local PTR lamp._wot._tcp.local"\n"lamp._wot._tcp.local SRV 1 0 80 lamp.local"\n"lamp._wot._tcp.local TXT td=/.well-known/wot;type=Thing"
as above
```suggestion
Thing ->  Consumer : mDNS response\n"_wot._tcp.local PTR lamp._wot._tcp.local"\n"lamp._wot._tcp.local SRV 1 0 80 lamp.local"\n"lamp._wot._tcp.local TXT td=/.well-known/wot;type=Thing"
```

2022-09-02 18:28 UTC, mmccool commented on index.html
>                  of discovery of Thing and <a>Thing Description Directory</a> using DNS-SD and mDNS.
```suggestion
                supporting discovery of a Thing or a <a>Thing Description Directory</a> using DNS-SD and mDNS. 
```

2022-09-02 18:28 UTC, mmccool commented on index.html
>                  <li>Description: Service name to search a Thing or a Thing Description Directory of W3C Web of Things</li>
```suggestion
                <li>Description: Service name to search for the Thing Description of a Thing or a Thing Description Directory in the W3C Web of Things</li>
```

2022-09-02 18:34 UTC, mmccool commented
Looks good, I suggested a few small changes to the images to make them clearer.  Captions in figure should be improved (github would not let me make suggestions on these lines...).  In the first figure, caption could be improve by saying "Using mDNS for discovery of the Thing Description of a Thing."  In the second figure, it should say "Using mDNS for discovery of the Thing Description of a Thing Description Directory (TDD)".

I notice also that the URLs that are returned here are .well-known/wot.  While this will often be the case if both well-known and DNS introductions are supported, this is not actually required, and DNS could return another URL that does not follow the .well-known structure (this is true also for other schemes, like Direct).  I don't know if we need another statement or example to make this clearer, or should avoid using .well-known in examples to avoid confusion/assumptions on the part of the reader.

2022-09-05 00:39 UTC, k-toumura commented
Thank you for your comment.  I've made the corrections as you indicated.

I also updated URLs to more neutral one: `/path/to/td`.

2022-09-05 14:35 UTC, mmccool commented
Discussion:
- Problem with many service names as in CoRE-RD is many rounds of broadcast needed
- Better if one request, parameters in option
- Propose adding an additional (optional) parameter in TXT, "scheme", with values of "http", "https", "coap", and "coaps", corresponding to "scheme" part of URL.  Defaults would be "http" for TCP and "coap" for UDP

2022-09-05 14:35 UTC, merged